'use strict';

const InputEnum = {
    'HDMI': 'HDMI',
    'HDMI1': 'HDMI1',
    'HDMI2': 'HDMI2',
    'HDMI3': 'HDMI3',
    'HDMI4': 'HDMI4',
    'HDMI5': 'HDMI5',
    'HDMI6': 'HDMI6',
    'HDMI7': 'HDMI7',
    'HDMI8': 'HDMI8',
    'AV': 'AV',
    'AV1': 'AV1',
    'AV2': 'AV2',
    'AV3': 'AV3',
    'AV4': 'AV4',
    'AV5': 'AV5',
    'AV6': 'AV6',
    'AV7': 'AV7',
    'AV8': 'AV8',
    'AUDIO': 'AUDIO',
    'AUDIO1': 'AUDIO1',
    'AUDIO2': 'AUDIO2',
    'AUDIO3': 'AUDIO3',
    'AUDIO4': 'AUDIO4',
    'AUDIO5': 'AUDIO5',
    'AUDIO6': 'AUDIO6',
    'AUDIO7': 'AUDIO7',
    'AUDIO8': 'AUDIO8',
    'TUNER': 'TUNER',
    'AUX': 'AUX',
    'V-AUX': 'V-AUX',
    'SERVER': 'SERVER',
    'NET_RADIO': 'NET RADIO',
    'USB': 'USB',
    'SPOTIFY': 'Spotify',
    'AIRPLAY': 'AirPlay',
    'DEEZER': 'Deezer',
    'BLUETOOTH': 'Bluetooth',
};

module.exports = InputEnum;
