'use strict';

const SurroundProgramEnum = {
    'MUNICH_A': 'munich_a',
    'MUNICH_B': 'munich_b',
    'MUNICH': 'munich',
    'FRANKFURT': 'frankfurt',
    'STUTTGART': 'stuttgart',
    'VIENNA': 'vienna',
    'AMSTERDAM': 'amsterdam',
    'USA_A': 'usa_a',
    'USA_B': 'usa_b',
    'TOKYO': 'tokyo',
    'FREIBURG': 'freiburg',
    'ROYAUMONT': 'royaumont',
    'CHAMBER': 'chamber',
    'CONCERT': 'concert',
    'VILLAGE_GATE': 'village_gate',
    'VILLAGE_VANGUARD': 'village_vanguard',
    'WAREHOUSE_LOFT': 'warehouse_loft',
    'CELLAR_CLUB': 'cellar_club',
    'JAZZ_CLUB': 'jazz_club',
    'ROXY_THEATRE': 'roxy_theatre',
    'BOTTOM_LINE': 'bottom_line',
    'ARENA': 'arena',
    'SPORTS': 'sports',
    'ACTION_GAME': 'action_game',
    'ROLEPLAYING_GAME': 'roleplaying_game',
    'GAME': 'game',
    'MUSIC_VIDEO': 'music_video',
    'MUSIC': 'music',
    'RECITAL_OPERA': 'recital_opera',
    'PAVILION': 'pavilion',
    'DISCO': 'disco',
    'STANDARD': 'standard',
    'SPECTACLE': 'spectacle',
    'SCI-FI': 'sci-fi',
    'ADVENTURE': 'adventure',
    'DRAMA': 'drama',
    'TALK_SHOW': 'talk_show',
    'TV_PROGRAM': 'tv_program',
    'MONO_MOVIE': 'mono_movie',
    'MOVIE': 'movie',
    'ENHANCED': 'enhanced',
    '2CH_STEREO': '2ch_stereo',
    '5CH_STEREO': '5ch_stereo',
    '7CH_STEREO': '7ch_stereo',
    '9CH_STEREO': '9ch_stereo',
    '11CH_STEREO': '11ch_stereo',
    'STEREO': 'stereo',
    'SURR_DECODER': 'surr_decoder',
    'MY_SURROUND': 'my_surround',
    'TARGET': 'target',
    'STRAIGHT': 'straight',
    'OFF': 'off',
};

module.exports = SurroundProgramEnum;